import RootLayoutWrapper from "./layout-wrapper";

export const metadata = {
  title: "Ironji",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <RootLayoutWrapper>{children}</RootLayoutWrapper>;
}